version: '3.4'

services:
  backend:
    build: .
    image: detectiononlinesexism_backend
    ports:
      - "8000:8000"
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: detectiononlinesexism_frontend
    ports:
      - "8080:8080"
    depends_on: [backend]