global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'fastapi-it'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000']
      
