# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - detectiononlinesexism

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0dabec118d9400d8af2825812731d5f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3b982d422ee540ed8daab708a305c469 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b0dabec118d9400d8af2825812731d5f }}/francebrescia / detectiononlinesexism_backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'detectiononlinesexism'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8eb8f127ab9149d786bbbfd2f0c3a7e5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b0dabec118d9400d8af2825812731d5f }}/francebrescia / detectiononlinesexism_backend:${{ github.sha }}'