# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - detectiononlinesexism

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://detectiononlinesexismcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ff285f64f7f547b694321f09f894c92f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b16df85049d4449b86b60742e587dcb8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: detectiononlinesexismcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ff285f64f7f547b694321f09f894c92f }}/detectiononlinesexismcontainer.azurecr.io/frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'detectiononlinesexism'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b72b7134af9b4f59883ad2fddfcff998 }}
        images: 'detectiononlinesexismcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ff285f64f7f547b694321f09f894c92f }}/detectiononlinesexismcontainer.azurecr.io/frontend:${{ github.sha }}'