name: Pydantic Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydantic
        pip install -U scikit-learn

    - name: Running Pydantic
      run: |
        python src/api/corpus_endpoint.py

    - name: Upload Pydantic Check Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pydantic-check-report
        path: pydantic_check_report.json
