name: Pylint

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Set up Python
      uses: actions/checkout@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Running Pylint
      run: |
        pylint src/ --output-format=json > pylint_report.json, colorized

    - name: Upload Pylint Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint_report.json
