name: pytest

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Set up Python
      uses: actions/checkout@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "import nltk; nltk.download('wordnet')"
        python -c "import nltk; nltk.download('omw-1.4')"

    - name: Copy data file
      run: |
        mkdir -p ../../data/Raw
        cp data/Raw/train_sexist.csv ../../data/Raw/

    - name: Run Pytest
      run: |
        python -m pytest -v -s

    - name: Upload Pylint Artifact

      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: pytest_report.json
