name: Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Set up Python
      uses: actions/checkout@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install pytest
        python -c "import nltk; nltk.download('wordnet')"
        python -c "import nltk; nltk.download('omw-1.4')"

    - name: Copy relevant files to artifacts
      run: |
        mkdir -p artifacts
        cp src/models/MLflow/test_a.py artifacts/
            cp src/models/MLflow/test_b.py artifacts/
            cp tests/behavioral_testing/test_directional_model_b.py artifacts/
            cp tests/behavioral_testing/test_invariance_model_a.py artifacts/
            cp tests/behavioral_testing/test_invariance_model_b.py artifacts/
            cp tests/behavioral_testing/test_minimum_functionality_model_a.py artifacts/
            cp tests/behavioral_testing/test_minimum_functionality_model_b.py artifacts/
            cp tests/dataset_testing/test_dataset_model_a.py artifacts/
            cp tests/dataset_testing/test_dataset_model_b.py artifacts/
  
    - name: Run Pytest
      run: |
        pytest

    - name: Upload Pytest Results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: reports/
