name: pytest

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Set up Python
      uses: actions/checkout@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clean Python cache files
      run: |
        find . -type f -name "__pycache__" -exec rm -r {} +
        find . -type f -name "*.pyc" -exec rm -f {} +


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "import nltk; nltk.download('wordnet')"
        python -c "import nltk; nltk.download('omw-1.4')"

    - name: Install OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev
    
    - name: Copy data file
      run: |
        mkdir -p ../../data/Raw
        cp data/Raw/train_sexist.csv ../../data/Raw
        mkdir -p $GITHUB_WORKSPACE/models/../../models
        cp models/validation_a.pkl $GITHUB_WORKSPACE/models/../../models
        cp models/validation_b.pkl $GITHUB_WORKSPACE/models/../../models

    - name: List current directory
      run: |
        ls -R

    - name: Run Pytest
      run: |
        python -m pytest -v -s

    - name: Upload Pytest Artifact

      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: pytest_report.json
